import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  CheckCircle2,
  Cpu,
  Printer,
  ScanLine,
  Save,
  Tag,
  XCircle,
} from 'lucide-react';
import { Link } from 'react-router-dom';
import Modal from '@/components/ui/Modal';
import {
  attachBarcodeWedgeListener,
  buildPrinterProfileFromKey,
  detectPrinterProfile,
  detectScannerProfile,
  loadSavedPrinter,
  savePrinterProfile,
  saveScannerRead,
} from '@/lib/labelDevices';
import {
  formatPresetSize,
  getDefaultProductPreset,
  getLogisticsLabelPresets,
  getProductLabelPresets,
  recommendPresetForPrinter,
  THERMAL_PRINTER_OPTIONS,
  type LabelPresetId,
} from '@/lib/labelPresets';
import { persistProductLabelIdentifiers } from '@/lib/persistProductLabelIdentifiers';
import {
  buildStockLabelHtml,
  printStockLabel,
  STOCK_LABEL_SPEC,
  type LabelPrintOptions,
  type StockLabelData,
} from '@/lib/printStockLabel';
import { classifyScanAgainstProduct, resolveProductIdentifiers } from '@/lib/productIdentifiers';
import { LOGSTOKA_ROUTES } from '@/lib/logstokaRoutes';
import { renderStockLabelAssets, type StockLabelRenderAssets } from '@/lib/stockLabelRender';
import './stockLabel.css';

export type StockLabelPersistContext = {
  productId: string;
  companyId: string | null;
  demo: boolean;
  sku: string;
};

type Props = {
  open: boolean;
  onClose: () => void;
  data: StockLabelData;
  persistContext?: StockLabelPersistContext;
  onIdentifiersPersisted?: () => void;
};

const StockLabelPreviewModal: React.FC<Props> = ({
  open,
  onClose,
  data,
  persistContext,
  onIdentifiersPersisted,
}) => {
  const [assets, setAssets] = useState<StockLabelRenderAssets | null>(null);
  const [scanTest, setScanTest] = useState('');
  const [printing, setPrinting] = useState(false);
  const [saving, setSaving] = useState(false);
  const [persisted, setPersisted] = useState(false);
  const [scannerTestMode, setScannerTestMode] = useState(false);
  const [lastWedgeRead, setLastWedgeRead] = useState<string | null>(null);

  const savedPrinter = loadSavedPrinter();
  const [printerKey, setPrinterKey] = useState(savedPrinter?.printerKey ?? 'elgin-l42');
  const [presetId, setPresetId] = useState<LabelPresetId>(
    savedPrinter?.presetId ?? getDefaultProductPreset().id,
  );

  const ids = useMemo(
    () =>
      resolveProductIdentifiers({
        id: persistContext?.productId ?? 'label-preview',
        sku: data.sku,
        internal_code: data.masterCode,
        barcode: data.barcode,
      }),
    [data.barcode, data.masterCode, data.sku, persistContext?.productId],
  );

  const printOptions: LabelPrintOptions = useMemo(() => ({ presetId }), [presetId]);

  const productPresets = useMemo(() => getProductLabelPresets(), []);
  const logisticsPresets = useMemo(() => getLogisticsLabelPresets(), []);
  const selectedPreset =
    [...productPresets, ...logisticsPresets].find((p) => p.id === presetId) ?? getDefaultProductPreset();

  const printerDetection = useMemo(() => detectPrinterProfile(), [printerKey, presetId]);
  const scannerDetection = useMemo(
    () => detectScannerProfile(),
    [lastWedgeRead, scanTest, scannerTestMode],
  );

  useEffect(() => {
    if (!open) return undefined;
    let cancelled = false;
    setAssets(null);
    setPersisted(false);
    setLastWedgeRead(null);
    const profile = loadSavedPrinter();
    if (profile) {
      setPrinterKey(profile.printerKey);
      setPresetId(profile.presetId);
    }
    void renderStockLabelAssets(data).then((next) => {
      if (!cancelled) setAssets(next);
    });
    return () => {
      cancelled = true;
    };
  }, [open, data]);

  useEffect(() => {
    if (!open || !scannerTestMode) return undefined;
    return attachBarcodeWedgeListener((value) => {
      setLastWedgeRead(value);
      setScanTest(value);
      saveScannerRead('Bipador USB (HID)', value);
    });
  }, [open, scannerTestMode]);

  const previewSrcDoc = useMemo(
    () => buildStockLabelHtml(data, true, assets ?? undefined, printOptions),
    [assets, data, printOptions],
  );

  const previewFrameStyle = useMemo(() => {
    const scale = Math.min(1, 420 / selectedPreset.widthMm, 260 / selectedPreset.heightMm) * 3.8;
    return {
      width: `${selectedPreset.widthMm * scale}px`,
      height: `${selectedPreset.heightMm * scale}px`,
    };
  }, [selectedPreset.heightMm, selectedPreset.widthMm]);

  const scanResult = useMemo(() => {
    const raw = scanTest.trim() || lastWedgeRead?.trim() || '';
    if (!raw) return null;
    return classifyScanAgainstProduct(raw, ids);
  }, [ids, lastWedgeRead, scanTest]);

  const needsPersist =
    Boolean(persistContext) &&
    (data.eanAutoGenerated || !persisted) &&
    data.masterCode.startsWith('LS');

  const handlePrinterChange = (key: string) => {
    setPrinterKey(key);
    const profile = buildPrinterProfileFromKey(key);
    setPresetId(profile.presetId);
  };

  const handlePresetChange = (next: LabelPresetId) => {
    setPresetId(next);
    const profile = loadSavedPrinter();
    if (profile) {
      savePrinterProfile({ ...profile, presetId: next });
    }
  };

  const persistIdentifiers = useCallback(async () => {
    if (!persistContext) return;
    setSaving(true);
    try {
      await persistProductLabelIdentifiers({
        companyId: persistContext.companyId,
        productId: persistContext.productId,
        sku: persistContext.sku,
        identifiers: ids,
        demo: persistContext.demo,
      });
      setPersisted(true);
      onIdentifiersPersisted?.();
    } catch (err) {
      window.alert(err instanceof Error ? err.message : 'Não foi possível salvar os códigos');
    } finally {
      setSaving(false);
    }
  }, [ids, onIdentifiersPersisted, persistContext]);

  const handlePrint = async () => {
    setPrinting(true);
    try {
      if (needsPersist && persistContext) {
        await persistIdentifiers();
      }
      buildPrinterProfileFromKey(printerKey);
      await printStockLabel(data, printOptions);
      onClose();
    } catch (err) {
      window.alert(err instanceof Error ? err.message : 'Não foi possível imprimir');
    } finally {
      setPrinting(false);
    }
  };

  const recommendedId = recommendPresetForPrinter(printerKey);
  const isLogisticsPreset = selectedPreset.category === 'logistics';

  return (
    <Modal
      open={open}
      title="Gerar etiqueta · LogStoka"
      subtitle={`Padrão estoque ${STOCK_LABEL_SPEC.size} · EAN-13 + QR · bipagem BR`}
      icon={<Tag size={18} strokeWidth={2.25} />}
      onClose={onClose}
      size="wide"
      footer={
        <div className="flex flex-wrap items-center justify-end gap-2">
          <button type="button" className="ls-btn-secondary" onClick={onClose}>
            Fechar
          </button>
          {persistContext ? (
            <button
              type="button"
              className="ls-btn-secondary"
              onClick={() => void persistIdentifiers()}
              disabled={saving || persisted}
            >
              <Save size={16} />
              {persisted ? 'Salvo no produto' : saving ? 'Salvando…' : 'Salvar códigos'}
            </button>
          ) : null}
          <button
            type="button"
            className="ls-btn-primary"
            onClick={() => void handlePrint()}
            disabled={printing || !assets}
          >
            <Printer size={16} />
            {printing ? 'Preparando…' : 'Imprimir etiqueta'}
          </button>
        </div>
      }
    >
      <div className="ls-stock-label-modal">
        <p className="ls-stock-label-modal__intro">
          Etiqueta de <strong>produto / estoque</strong> (prateleira, separação, inventário). Código mestre{' '}
          <strong>{data.masterCode}</strong>, EAN escaneável e QR. O mesmo produto usa sempre os mesmos códigos — 1 milhão
          de unidades, uma identificação; novo modelo ou cor = novo cadastro.
          {data.eanAutoGenerated
            ? ' EAN gerado uma vez para este produto — salve antes de imprimir para não duplicar em outro item.'
            : null}
        </p>

        <div className="ls-stock-label-modal__devices">
          <section className="ls-stock-label-modal__device-card">
            <h3 className="ls-stock-label-modal__device-title">
              <Printer size={14} aria-hidden />
              Impressora
            </h3>
            <p className="ls-stock-label-modal__device-hint">{printerDetection.message}</p>
            <label className="ls-stock-label-modal__field-label" htmlFor="ls-label-printer">
              Modelo térmico (perfil salvo neste computador)
            </label>
            <select
              id="ls-label-printer"
              className="ls-stock-label-modal__select"
              value={printerKey}
              onChange={(e) => handlePrinterChange(e.target.value)}
            >
              {THERMAL_PRINTER_OPTIONS.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.brand} {p.model}
                </option>
              ))}
            </select>
            {printerDetection.status === 'configured' ? (
              <p className="ls-stock-label-modal__device-ok">
                <CheckCircle2 size={14} />
                {printerDetection.profile?.displayName}
              </p>
            ) : null}
            <p className="ls-stock-label-modal__device-note">
              O navegador não lista USB automaticamente; na impressão escolha a fila real (Zebra, Elgin, etc.).
            </p>
          </section>

          <section className="ls-stock-label-modal__device-card">
            <h3 className="ls-stock-label-modal__device-title">
              <ScanLine size={14} aria-hidden />
              Bipador / scanner
            </h3>
            <p className="ls-stock-label-modal__device-hint">{scannerDetection.message}</p>
            <button
              type="button"
              className={`ls-btn-secondary ls-stock-label-modal__test-scan ${scannerTestMode ? 'is-active' : ''}`}
              onClick={() => setScannerTestMode((v) => !v)}
            >
              {scannerTestMode ? 'Teste ativo — bipar agora' : 'Testar bipador'}
            </button>
            {lastWedgeRead ? (
              <p className="ls-stock-label-modal__device-ok">
                <CheckCircle2 size={14} />
                Leitura: {lastWedgeRead}
              </p>
            ) : null}
          </section>
        </div>

        <div className="ls-stock-label-modal__sizes">
          <div>
            <span className="ls-stock-label-modal__sizes-label">Tamanho · estoque</span>
            <div className="ls-stock-label-modal__size-chips">
              {productPresets.map((p) => (
                <button
                  key={p.id}
                  type="button"
                  className={`ls-stock-label-modal__size-chip ${presetId === p.id ? 'is-selected' : ''} ${
                    p.isDefault ? 'is-default' : ''
                  }`}
                  onClick={() => handlePresetChange(p.id)}
                >
                  {formatPresetSize(p)}
                  {p.isDefault ? ' · padrão' : ''}
                </button>
              ))}
            </div>
          </div>
          <div>
            <span className="ls-stock-label-modal__sizes-label">Logística / transporte</span>
            <div className="ls-stock-label-modal__size-chips">
              {logisticsPresets.map((p) => (
                <button
                  key={p.id}
                  type="button"
                  className={`ls-stock-label-modal__size-chip ls-stock-label-modal__size-chip--logistics ${
                    presetId === p.id ? 'is-selected' : ''
                  }`}
                  onClick={() => handlePresetChange(p.id)}
                >
                  {formatPresetSize(p)}
                </button>
              ))}
            </div>
          </div>
          {recommendedId === presetId ? (
            <p className="ls-stock-label-modal__recommend">
              Tamanho recomendado para esta impressora: <strong>{formatPresetSize(selectedPreset)}</strong>
            </p>
          ) : (
            <p className="ls-stock-label-modal__recommend">
              Sugestão para esta impressora:{' '}
              <button
                type="button"
                className="ls-stock-label-modal__recommend-link"
                onClick={() => handlePresetChange(recommendedId)}
              >
                {formatPresetSize(
                  [...productPresets, ...logisticsPresets].find((p) => p.id === recommendedId) ??
                    getDefaultProductPreset(),
                )}
              </button>
            </p>
          )}
        </div>

        {isLogisticsPreset ? (
          <p className="ls-stock-label-modal__logistics-warn">
            Formato de <strong>expedição</strong> (caixa / Correios). Para prateleira use 100×50 mm. Etiqueta SEDEX
            completa virá no módulo expedição.
          </p>
        ) : null}

        <div className="ls-stock-label-modal__preview">
          <iframe
            title="Preview da etiqueta"
            srcDoc={previewSrcDoc}
            className="ls-stock-label-modal__iframe"
            style={previewFrameStyle}
          />
        </div>

        <dl className="ls-stock-label-modal__spec">
          <div>
            <dt>Código interno</dt>
            <dd>{data.masterCode}</dd>
          </div>
          <div>
            <dt>EAN / GTIN</dt>
            <dd>
              {data.barcode}
              {data.eanAutoGenerated ? <span className="ls-stock-label-modal__badge">Gerado</span> : null}
            </dd>
          </div>
          <div>
            <dt>QR Code</dt>
            <dd className="ls-stock-label-modal__qr-text">{data.qrPayload}</dd>
          </div>
          <div>
            <dt>Tamanho</dt>
            <dd>{formatPresetSize(selectedPreset)}</dd>
          </div>
          <div>
            <dt>SKU marketplace</dt>
            <dd>{data.sku}</dd>
          </div>
          <div>
            <dt>Quantidade</dt>
            <dd>
              {data.quantity} {data.unit ?? 'UN'}
            </dd>
          </div>
        </dl>

        <div className="ls-stock-label-modal__scan-test">
          <label className="ls-stock-label-modal__scan-label" htmlFor="ls-label-scan-test">
            <ScanLine size={14} aria-hidden />
            Testar leitura (digite ou use o bipador)
          </label>
          <input
            id="ls-label-scan-test"
            type="text"
            className="ls-stock-label-modal__scan-input"
            placeholder="LS000001, EAN ou URL do QR…"
            value={scanTest}
            onChange={(e) => setScanTest(e.target.value)}
          />
          {scanResult ? (
            <p
              className={`ls-stock-label-modal__scan-result ${
                scanResult.matches ? 'ls-stock-label-modal__scan-result--ok' : 'ls-stock-label-modal__scan-result--fail'
              }`}
            >
              {scanResult.matches ? <CheckCircle2 size={14} /> : <XCircle size={14} />}
              {scanResult.matches
                ? `Produto identificado (${scanResult.kind === 'internal' ? 'código LS' : scanResult.kind === 'ean' ? 'EAN/GTIN' : scanResult.kind === 'qr' ? 'QR Code' : 'SKU'})`
                : 'Leitura não corresponde a este produto'}
            </p>
          ) : null}
        </div>

        <p className="ls-stock-label-modal__devices-link">
          <Cpu size={14} aria-hidden />
          <Link to={`${LOGSTOKA_ROUTES.SETTINGS}/dispositivos`}>Central de dispositivos</Link>
          — impressoras, bipadores e última atividade.
        </p>

        <ul className="ls-stock-label-modal__fields">
          {STOCK_LABEL_SPEC.fields.map((field) => (
            <li key={field}>{field}</li>
          ))}
        </ul>
      </div>
    </Modal>
  );
};

export default StockLabelPreviewModal;
