import type { CSSProperties } from 'react';

/**
 * Menu lateral de secções (233px + borda), alinhado ao padrão Usage/Supabase.
 */
export const HUB_MASTER_SECTION_NAV: Record<string, CSSProperties> = {
  layout: {
    display: 'grid',
    gridTemplateColumns: '233px 1fr',
    gap: 0,
    alignItems: 'flex-start',
  },
  sidebarWrapper: {
    position: 'sticky',
    top: '0',
    alignSelf: 'flex-start',
    maxHeight: '508px',
  },
  sidebar: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    width: 233,
    boxSizing: 'border-box',
    minHeight: 'min(650px, calc(100vh - 120px))',
    marginLeft: 0,
    marginRight: 0,
    overflowY: 'auto',
    overflowX: 'hidden',
    backgroundColor: 'transparent',
    padding: '11px 0',
    borderRadius: 0,
    border: 'none',
    borderRight: '1px solid #E5E7EB',
    scrollbarWidth: 'thin',
    scrollbarColor: '#CBD5E1 transparent',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },
  sidebarHeading: {
    margin: '0 26px',
    fontSize: '15px',
    fontWeight: 600,
    color: '#1a1d21',
    letterSpacing: '-0.02em',
    lineHeight: 1.3,
  },
  sidebarHeadingRule: {
    height: 1,
    backgroundColor: '#eceef1',
    margin: '12px 26px 14px',
    borderRadius: 1,
    flexShrink: 0,
  },
  sidebarSection: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    gap: 0,
    marginLeft: 15,
    marginRight: 15,
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },
  sidebarSectionRule: {
    height: 1,
    backgroundColor: '#F1F5F9',
    margin: '8px 15px 6px',
    flexShrink: 0,
  },
  sidebarSectionLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#6b7280',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    padding: '0 0 4px',
    lineHeight: 1.3,
    marginLeft: 0,
    marginRight: 0,
  },
  sidebarSectionItems: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  main: {
    backgroundColor: '#FFFFFF',
    marginLeft: 26,
    marginRight: 26,
    paddingTop: 37,
    paddingBottom: 64,
    paddingLeft: 0,
    paddingRight: 0,
    borderRadius: 0,
    border: 'none',
    boxShadow: 'none',
    minHeight: 'min(922px, calc(100vh - 120px))',
    marginTop: 0,
    marginBottom: 0,
    position: 'relative',
    boxSizing: 'border-box',
  },
  mainInner: {
    display: 'flex',
    flexDirection: 'column',
    gap: 13,
    marginLeft: 15,
    marginRight: 15,
    minHeight: 0,
    boxSizing: 'border-box',
  },
};
