import type { CSSProperties } from 'react';

/**
 * Layout do Master Hub igual ao `/master/logta` (referência única para LogDock,
 * Zaptro, Gateway IA, Créditos e demais consoles de produto).
 */
export const HUB_MASTER_PRODUCT_SHELL: Record<string, CSSProperties> = {
  container: {
    display: 'flex',
    flex: 1,
    backgroundColor: 'var(--hub-bg)',
    minHeight: 'calc(100vh - 56px)',
    overflow: 'visible',
  },
  secondarySidebar: {
    width: '260px',
    borderRight: '1px solid var(--hub-border)',
    backgroundColor: 'var(--hub-sidebar-bg)',
    display: 'flex',
    flexDirection: 'column',
    flexShrink: 0,
    paddingTop: 0,
    gap: 0,
  },
  sidebarHeader: {
    padding: '18px 20px',
    fontSize: '14px',
    fontWeight: '800',
    color: 'var(--hub-text-main)',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  sidebarNav: {
    padding: '8px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '0px',
    overflowY: 'auto',
    flex: 1,
  },
  sidebarBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '5px 12px',
    borderRadius: '100px',
    border: 'none',
    fontSize: '12px',
    fontWeight: '900',
    textTransform: 'none',
    letterSpacing: '0.02em',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'background-color 0.1s',
    width: '100%',
  },
  contentArea: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    overflowY: 'auto',
    gap: 0,
    backgroundColor: 'var(--hub-bg)',
    color: 'var(--hub-text-main)',
  },
  content: {
    padding:
      'var(--hub-master-page-pad-top) var(--hub-master-page-pad-x) var(--hub-master-page-pad-bottom) var(--hub-master-page-pad-x)',
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    marginLeft: 'var(--hub-master-page-margin-x)',
    marginRight: 'var(--hub-master-page-margin-x)',
  },
  actionBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '10px 24px',
    borderRadius: '100px',
    border: '1px solid var(--hub-border)',
    backgroundColor: 'var(--hub-card)',
    color: 'var(--hub-text-main)',
    fontSize: '13px',
    fontWeight: '900',
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: 'var(--hub-shadow-card)',
    fontFamily: 'Inter, system-ui, sans-serif',
    textTransform: 'uppercase',
    letterSpacing: '0.02em',
  },
  card: {
    backgroundColor: 'var(--hub-card)',
    borderRadius: '12px',
    padding: '24px',
    border: '1px solid var(--hub-border)',
    boxShadow: 'var(--hub-shadow-card)',
  },
  metricLabel: {
    fontSize: '11px',
    fontWeight: '800',
    color: 'var(--hub-text-muted)',
    marginBottom: '8px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  metricValue: {
    fontSize: '28px',
    fontWeight: '900',
    color: 'var(--hub-text-main)',
  },
};

/** Título de grupo na sidebar (PROJETO, OPERAÇÃO, …) — mesmo do Logta Admin. */
export const hubMasterSidebarSectionTitleStyle: CSSProperties = {
  fontSize: '11px',
  fontWeight: '500',
  color: 'var(--hub-text-muted)',
  textTransform: 'uppercase',
  letterSpacing: '0.05em',
  padding: '4px 10px 6px',
};
