import {
  getDefaultProductPreset,
  resolveLabelDimensions,
  type LabelPresetId,
} from '@/lib/labelPresets';
import type { StockLabelRenderAssets } from '@/lib/stockLabelRender';

export type StockLabelContext = 'return' | 'product' | 'movement' | 'picking';

export type StockLabelData = {
  /** Código mestre LogStoka (LS000001) — nunca substituído na etiqueta */
  masterCode: string;
  /** SKU comercial / marketplace (referência secundária) */
  sku: string;
  productName: string;
  /** EAN-13 / GTIN escaneável (real na etiqueta) */
  barcode: string;
  /** URL ou texto embutido no QR Code */
  qrPayload: string;
  eanAutoGenerated?: boolean;
  category?: string;
  quantity: number;
  unit?: string;
  context?: StockLabelContext;
  reference?: string;
  subtitle?: string;
};

export type LabelPrintOptions = {
  presetId?: LabelPresetId;
  widthMm?: number;
  heightMm?: number;
};

const CONTEXT_LABELS: Record<StockLabelContext, string> = {
  return: 'DEVOLUÇÃO WMS',
  product: 'ESTOQUE WMS',
  movement: 'MOVIMENTAÇÃO',
  picking: 'SEPARAÇÃO',
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function placeholderBarcodeBlock(ean: string): string {
  const digits = ean.replace(/\D/g, '') || '0000000000000';
  let bars = '';
  for (let i = 0; i < Math.min(digits.length, 20); i += 1) {
    const n = Number(digits[i]) || 0;
    const w = n % 2 === 0 ? 2 : 3;
    bars += `<span style="display:inline-block;width:${w}px;height:100%;background:#111;margin-right:1px"></span>`;
  }
  return `<div class="bars bars--loading">${bars}</div>`;
}

export function buildStockLabelHtml(
  data: StockLabelData,
  forPreview = false,
  assets?: StockLabelRenderAssets,
  options?: LabelPrintOptions,
): string {
  const presetId = options?.presetId ?? 'stock';
  const { widthMm, heightMm, preset } = resolveLabelDimensions(presetId, {
    widthMm: options?.widthMm,
    heightMm: options?.heightMm,
  });
  const isLogistics = preset.category === 'logistics';
  const compact = heightMm <= 40;
  const ctx = data.context ?? 'product';
  const ctxLabel = CONTEXT_LABELS[ctx];
  const ean = data.barcode.replace(/\D/g, '').slice(0, 13);
  const qty = `${data.quantity} ${data.unit?.trim() || 'UN'}`;
  const ref = data.reference?.trim() ? escapeHtml(data.reference) : '—';
  const nameMax = compact ? 28 : heightMm >= 100 ? 60 : 52;
  const name = escapeHtml(data.productName.slice(0, nameMax));
  const master = escapeHtml(data.masterCode);
  const skuLine =
    data.sku && data.sku !== data.masterCode && !compact
      ? `<span class="sku-alt">SKU ${escapeHtml(data.sku)}</span>`
      : '';
  const subtitle = data.subtitle && !compact ? `<p class="sub">${escapeHtml(data.subtitle)}</p>` : '';
  const category =
    data.category?.trim() && !compact
      ? `<span class="cat">${escapeHtml(data.category.slice(0, 24))}</span>`
      : '';
  const eanNote = data.eanAutoGenerated && !compact ? '<span class="ean-note">EAN LogStoka</span>' : '';
  const logisticsBanner = isLogistics
    ? '<p class="logistics-note">Formato logístico — etiqueta de transporte (Correios/ML) usa módulo expedição. Conteúdo abaixo: identificação do produto.</p>'
    : '';

  const qrPx = Math.round(Math.min(72, Math.max(40, heightMm * 1.1)));
  const eanHuman = escapeHtml(ean.replace(/(\d{3})(\d{4})(\d{5})(\d)/, '$1 $2 $3 $4'));
  const eanLine = `<div class="ean-line">
        <span class="ean">EAN ${eanHuman}</span>
        ${eanNote}
      </div>`;

  const barcodeBlock = assets
    ? `<div class="barcode-row">
        <div class="barcode-stack">
          <div class="barcode-ean">${assets.eanSvg}</div>
          ${eanLine}
        </div>
        <img class="qr" src="${assets.qrDataUrl}" alt="QR ${master}" width="${qrPx}" height="${qrPx}" />
      </div>`
    : `<div class="barcode-row barcode-row--loading">
        <div class="barcode-stack">
          ${placeholderBarcodeBlock(ean)}
          ${eanLine}
        </div>
        <div class="qr qr--placeholder" aria-hidden="true"></div>
      </div>`;

  const footBlock = compact
    ? `<div class="foot foot--compact"><span class="qty">Qtd ${escapeHtml(qty)}</span></div>`
    : `<div class="foot">
      <span>Ref: ${ref}</span>
      <span class="qty">Qtd ${escapeHtml(qty)}</span>
    </div>`;

  const pageStyle = forPreview
    ? ''
    : `@page { size: ${widthMm}mm ${heightMm}mm; margin: 2mm; }
       @media print { body { margin: 0; } .label { box-shadow: none !important; } }`;

  const masterFont = compact ? '11px' : heightMm >= 100 ? '18px' : '16px';
  const nameFont = compact ? '6px' : '7.5px';
  const qrSize = compact ? '10mm' : `${Math.min(16, heightMm * 0.28)}mm`;

  return `<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8" />
  <title>Etiqueta ${master}</title>
  <style>
    ${pageStyle}
    * { box-sizing: border-box; }
    body { font-family: system-ui, -apple-system, sans-serif; margin: 0; padding: ${forPreview ? '0' : '2mm'}; background: ${forPreview ? 'transparent' : '#fff'}; }
    .label {
      width: ${widthMm}mm;
      height: ${heightMm}mm;
      border: 1px solid #d4d4d4;
      border-radius: 4px;
      padding: ${compact ? '1.5mm 2mm' : '2.5mm 3.5mm'};
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      background: #fff;
      ${forPreview ? 'box-shadow: 0 8px 24px rgba(0,0,0,0.08);' : ''}
    }
    .logistics-note {
      margin: 0 0 1mm;
      padding: 1mm 1.5mm;
      border-radius: 2px;
      font-size: 5px;
      font-weight: 700;
      line-height: 1.3;
      color: #9a3412;
      background: #fff7ed;
      border: 1px solid #fed7aa;
    }
    .head { display: flex; justify-content: space-between; align-items: center; gap: 4px; }
    .brand { font-size: ${compact ? '5px' : '6.5px'}; font-weight: 900; letter-spacing: 0.12em; color: #ea580c; text-transform: uppercase; }
    .ctx { font-size: ${compact ? '5px' : '6.5px'}; font-weight: 800; color: #525252; letter-spacing: 0.06em; }
    .name { font-size: ${nameFont}; font-weight: 800; color: #171717; line-height: 1.2; max-height: ${compact ? '6mm' : '9mm'}; overflow: hidden; margin: 1mm 0 0.5mm; }
    .sub { font-size: 6.5px; font-weight: 600; color: #737373; margin: 0.5mm 0 0; }
    .master { font-size: ${masterFont}; font-weight: 900; letter-spacing: 0.04em; color: #111; line-height: 1; }
    .meta { display: flex; flex-wrap: wrap; align-items: center; gap: 3px 6px; margin-top: 0.5mm; }
    .sku-alt { font-size: 6.5px; font-weight: 700; color: #525252; }
    .cat { font-size: 6px; font-weight: 700; color: #737373; text-transform: uppercase; letter-spacing: 0.04em; }
    .barcode-row { display: flex; align-items: flex-end; justify-content: space-between; gap: 2mm; margin-top: 0.5mm; }
    .barcode-stack {
      flex: 1;
      min-width: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    .barcode-ean {
      width: 100%;
      display: flex;
      justify-content: center;
      align-items: flex-end;
      overflow: hidden;
    }
    .barcode-ean svg {
      width: auto;
      max-width: 100%;
      height: auto;
      max-height: ${compact ? '7mm' : '11mm'};
      display: block;
      margin: 0 auto;
    }
    .qr { width: ${qrSize}; height: ${qrSize}; flex-shrink: 0; object-fit: contain; align-self: flex-end; }
    .qr--placeholder { border: 1px dashed #d4d4d4; border-radius: 2px; background: #fafafa; min-width: ${qrSize}; min-height: ${qrSize}; align-self: flex-end; }
    .bars { width: 100%; max-width: 52mm; height: ${compact ? '7mm' : '11mm'}; display: flex; align-items: flex-end; justify-content: center; overflow: hidden; margin: 0 auto; }
    .bars--loading { opacity: 0.35; }
    .ean-line {
      width: 100%;
      max-width: 52mm;
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: center;
      gap: 3px 5px;
      margin-top: 0.6mm;
      text-align: center;
    }
    .ean {
      font-size: ${compact ? '6px' : '7.5px'};
      font-weight: 800;
      letter-spacing: 0.06em;
      font-variant-numeric: tabular-nums;
      color: #111;
      line-height: 1.1;
      white-space: nowrap;
    }
    .ean-note { font-size: 5.5px; font-weight: 800; color: #ea580c; text-transform: uppercase; letter-spacing: 0.06em; }
    .foot { display: flex; justify-content: space-between; align-items: flex-end; font-size: 6.5px; font-weight: 800; color: #525252; margin-top: 0.5mm; }
    .foot--compact { justify-content: flex-end; }
    .qty { font-size: ${compact ? '8px' : '10px'}; font-weight: 900; color: #ea580c; }
  </style>
</head>
<body>
  <div class="label">
    <div>
      ${logisticsBanner}
      <div class="head">
        <span class="brand">LogStoka</span>
        <span class="ctx">${ctxLabel}</span>
      </div>
      <div class="name">${name}</div>
      ${subtitle}
      <div class="master">${master}</div>
      <div class="meta">${skuLine}${category}</div>
    </div>
    <div>
      ${barcodeBlock}
    </div>
    ${footBlock}
  </div>
  ${forPreview ? '' : `<script>window.onload=function(){window.print();window.onafterprint=function(){window.close();};}</script>`}
</body>
</html>`;
}

function openPrintDocument(html: string): Window | null {
  const win = window.open('', '_blank', 'noopener,noreferrer,width=520,height=360');
  if (!win) return null;
  win.document.write(html);
  win.document.close();
  return win;
}

export async function printStockLabel(data: StockLabelData, options?: LabelPrintOptions): Promise<void> {
  const { renderStockLabelAssets } = await import('@/lib/stockLabelRender');
  const assets = await renderStockLabelAssets(data);
  const html = buildStockLabelHtml(data, false, assets, options);
  const win = openPrintDocument(html);
  if (!win) {
    throw new Error('Permita pop-ups para imprimir a etiqueta');
  }
}

export const STOCK_LABEL_SPEC = {
  defaultPreset: getDefaultProductPreset(),
  size: '100 × 50 mm (padrão estoque)',
  type: 'Térmica (Zebra, Elgin, Argox, Gprinter, TSC, Brother)',
  fields: [
    'Nome do produto',
    'Código interno LogStoka (LS)',
    'EAN-13 / GTIN (barras reais)',
    'QR Code (consulta e bipagem)',
    'SKU marketplace (se diferente)',
    'Quantidade e referência WMS',
  ],
};
