import type { StockLabelContext, StockLabelData } from '@/lib/printStockLabel';
import { resolveProductIdentifiers } from '@/lib/productIdentifiers';
import type { DemoMovementRow } from '@/lib/logstokaDemoSeed';
import type { LsProduct } from '@/types';

export const EMPTY_STOCK_LABEL: StockLabelData = {
  masterCode: '—',
  sku: '—',
  productName: '—',
  barcode: '0000000000000',
  qrPayload: 'https://logstoka.com.br/p/—',
  quantity: 1,
};

type ProductRef = Pick<LsProduct, 'id' | 'sku' | 'name' | 'barcode' | 'internal_code' | 'unit' | 'category_id'> | null | undefined;

function movementContext(type: string): StockLabelContext {
  if (type === 'return') return 'return';
  if (type === 'exit') return 'picking';
  return 'movement';
}

function labelFromProductRef(product: ProductRef, base: Omit<StockLabelData, 'masterCode' | 'barcode' | 'qrPayload' | 'sku' | 'eanAutoGenerated'> & { sku?: string }): StockLabelData {
  if (!product) {
    const sku = base.sku ?? '—';
    const ids = resolveProductIdentifiers({ id: 'prod-0', sku, internal_code: sku.startsWith('LS') ? sku : null, barcode: null });
    return {
      ...base,
      masterCode: ids.masterCode,
      sku: ids.marketplaceSku,
      barcode: ids.ean13,
      qrPayload: ids.qrPayload,
      eanAutoGenerated: ids.eanGenerated,
    };
  }

  const ids = resolveProductIdentifiers(product);
  return {
    ...base,
    masterCode: ids.masterCode,
    sku: ids.marketplaceSku,
    barcode: ids.ean13,
    qrPayload: ids.qrPayload,
    eanAutoGenerated: ids.eanGenerated,
    unit: base.unit ?? product.unit ?? 'UN',
  };
}

export function stockLabelFromMovement(
  movement: Pick<
    DemoMovementRow,
    'sku' | 'product_name' | 'total_quantity' | 'reference_code' | 'id' | 'movement_type'
  >,
  product?: ProductRef,
): StockLabelData {
  return labelFromProductRef(product, {
    sku: movement.sku ?? '',
    productName: movement.product_name ?? movement.sku ?? '',
    quantity: movement.total_quantity,
    unit: product?.unit ?? 'UN',
    context: movementContext(movement.movement_type),
    reference: movement.reference_code ?? movement.id,
  });
}

export function stockLabelFromProduct(
  product: Pick<LsProduct, 'id' | 'sku' | 'name' | 'barcode' | 'internal_code' | 'unit' | 'category_id'>,
  quantity = 1,
): StockLabelData {
  return labelFromProductRef(product, {
    productName: product.name,
    quantity,
    unit: product.unit ?? 'UN',
    context: 'product',
    reference: resolveProductIdentifiers(product).masterCode,
  });
}

export function stockLabelFromReturn(
  item: { sku: string; product_name: string; quantity: number; order_reference?: string | null; id: string; reason?: string | null },
  product?: ProductRef,
): StockLabelData {
  return labelFromProductRef(product, {
    sku: item.sku,
    productName: item.product_name,
    quantity: item.quantity,
    unit: product?.unit ?? 'UN',
    context: 'return',
    reference: item.order_reference ?? item.id,
    subtitle: item.reason ?? undefined,
  });
}
